### ISSUE TITLE
TSDB: Timestamp cannot be older than the latest timestamp in the time series

### ISSUE THREAD

**Issue by iamshreeram** [RedisTimeSeries/redis-weather#1]
Hi @alex6058 , Seeing below error -

```
redis-weather-app | Traceback (most recent call last):
redis-weather-app |   File "openweather_redis_exporter.py", line 176, in <module>
redis-weather-app |     ts_add_weather(ts_night,'temp',location,'hourly',dt['temp']['night'])
redis-weather-app |   File "openweather_redis_exporter.py", line 37, in ts_add_weather
redis-weather-app |     r.execute_command('ts.add', key_name, ts, value)
redis-weather-app |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
redis-weather-app |     return self.parse_response(conn, command_name, **options)
redis-weather-app |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
redis-weather-app |     response = connection.read_response()
redis-weather-app |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
redis-weather-app |     raise response
redis-weather-app | redis.exceptions.ResponseError: TSDB: Timestamp cannot be older than the latest timestamp in the time series
redis-weather-app exited with code 1
```

**Comment by iamshreeram** [comment]
@alex6058 , @mikhailredis - There is some issue with this. Can you try the latest one in your local and let us know.

**Comment by alex6058** [comment]
Hello @iamshreeram 

I believe I fixed it. Can you please check and let me know? 

Thank you

**Comment by iamshreeram** [comment]
Hello @alex6058 , Yes. It is working now. thanks! Is it because of Duplicate records? 
By reading the exception (`TSDB: Timestamp cannot be older than the latest timestamp in the time series`), I thought the Redis TSDB doesn't allow inserting older records. The exception of Redis client / Redis TSDB needs to be checked.

**Comment by mikhailredis** [comment]
@iamshreeram Redis TimeSeries v1.4 introduced DUPLICATE_POLICY https://github.com/RedisTimeSeries/RedisTimeSeries/releases/tag/v1.4.5, which Alexey used in the update.
